name: Publish ApplicationRecord to Registry
on:
  release:
    types: [published]
  push:
    branches:
      - main
      - '*'

env:
  CERC_REGISTRY_USER_KEY: "6772bf9c4fcda387e9ca29ed52c4bd9015ff8e24e028c0f8f8299b869decc52e"
  CERC_REGISTRY_BOND_ID: "e4b46f52fdbaf32d86ac38989b0f52f091534cbe20eac12401d3f5cd0e27c27e"

jobs:
  cns_publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone project repository"
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # though you need version 14 with geojson
      - name: "Install Yarn"
        run: |
          npm install -g yarn
          npm install -g typescript

      - name: "Install registry CLI"
        run: |
          npm config set @cerc-io:registry https://git.vdb.to/api/packages/cerc-io/npm/
          yarn global add @cerc-io/laconic-registry-cli
          laconic --version
      - name: "Install jq"
        uses: dcarbone/install-jq-action@v2.1.0
      - name: "Publish App Record"
        run: scripts/publish-app-record.sh
